#include "Game.h"

Dictionary *COUNTRIES;
int COUNTRIES_COUNT = 191;

void add_country(Dictionary* list, char* country, char* continent, char* language, char* population, char* currency, char* borders, char* colors) {
    add_entry(list, country, continent);
    add_entry(list, country, language);
    add_entry(list, country, population);
    add_entry(list, country, currency);
    add_entry(list, country, borders);
    add_entry(list, country, colors);
}

void load_countries() {
    COUNTRIES = create_dictionary();
    // 191 pays
    add_country(COUNTRIES, "Afghanistan", "Asie", "Dari, Pashto", "38000000", "Afghani", "6", "Noir, Rouge, Vert");
    add_country(COUNTRIES, "Albanie", "Europe", "Albanais", "2800000", "Lek", "4", "Rouge, Noir");
    add_country(COUNTRIES, "Algerie", "Afrique", "Arabe", "43000000", "Dinar algerien", "6", "Vert, Blanc, Rouge");
    add_country(COUNTRIES, "Andorre", "Europe", "Catalan", "77000", "Euro", "2", "Bleu, Jaune, Rouge");
    add_country(COUNTRIES, "Angola", "Afrique", "Portugais", "31000000", "Kwanza", "4", "Rouge, Noir");
    add_country(COUNTRIES, "Antigua-et-Barbuda", "Amerique", "Anglais", "97000", "Dollar des Caraibes orientales", "0", "Rouge, Noir, Bleu, Blanc");
    add_country(COUNTRIES, "Argentine", "Amerique", "Espagnol", "45000000", "Peso argentin", "5", "Bleu, Blanc");
    add_country(COUNTRIES, "Armenie", "Asie", "Armenien", "3000000", "Dram", "4", "Rouge, Bleu, Orange");
    add_country(COUNTRIES, "Australie", "Oceanie", "Anglais", "25000000", "Dollar australien", "0", "Bleu, Blanc, Rouge");
    add_country(COUNTRIES, "Autriche", "Europe", "Allemand", "9000000", "Euro", "8", "Rouge, Blanc");
    add_country(COUNTRIES, "Azerbaidjan", "Asie", "Azeri", "10000000", "Manat", "5", "Bleu, Rouge, Vert");
    add_country(COUNTRIES, "Bahamas", "Amerique", "Anglais", "389000", "Dollar bahameen", "0", "Bleu, Jaune, Noir");
    add_country(COUNTRIES, "Bahrein", "Asie", "Arabe", "1700000", "Dinar bahreini", "1", "Rouge, Blanc");
    add_country(COUNTRIES, "Bangladesh", "Asie", "Bengali", "164000000", "Taka", "2", "Vert, Rouge");
    add_country(COUNTRIES, "Barbade", "Amerique", "Anglais", "287000", "Dollar barbadien", "0", "Bleu, Jaune, Noir");
    add_country(COUNTRIES, "Belgique", "Europe", "Neerlandais, Français, Allemand", "11500000", "Euro", "4", "Noir, Jaune, Rouge");
    add_country(COUNTRIES, "Belize", "Amerique", "Anglais", "397000", "Dollar belizeen", "2", "Bleu, Rouge, Blanc");
    add_country(COUNTRIES, "Benin", "Afrique", "Français", "12000000", "Franc CFA", "4", "Vert, Rouge, Jaune");
    add_country(COUNTRIES, "Bhoutan", "Asie", "Dzongkha", "763000", "Ngultrum", "2", "Orange, Blanc");
    add_country(COUNTRIES, "Bolivie", "Amerique", "Espagnol, Quechua, Aymara", "11500000", "Boliviano", "5", "Rouge, Jaune, Vert");
    add_country(COUNTRIES, "Bosnie-Herzegovine", "Europe", "Bosniaque, Croate, Serbe", "3300000", "Mark convertible", "5", "Bleu, Jaune");
    add_country(COUNTRIES, "Botswana", "Afrique", "Anglais, Tswana", "2300000", "Pula", "4", "Bleu, Noir, Blanc");
    add_country(COUNTRIES, "Bresil", "Amerique", "Portugais", "212000000", "Real", "10", "Vert, Jaune, Bleu");
    add_country(COUNTRIES, "Brunei", "Asie", "Malais", "437000", "Dollar bruneien", "2", "Jaune, Blanc, Noir");
    add_country(COUNTRIES, "Bulgarie", "Europe", "Bulgare", "7000000", "Lev", "5", "Blanc, Vert, Rouge");
    add_country(COUNTRIES, "Burkina Faso", "Afrique", "Français", "20000000", "Franc CFA", "6", "Rouge, Vert");
    add_country(COUNTRIES, "Burundi", "Afrique", "Kirundi, Français", "11000000", "Franc burundais", "3", "Rouge, Vert, Blanc");
    add_country(COUNTRIES, "Cambodge", "Asie", "Khmer", "16000000", "Riel", "3", "Bleu, Rouge");
    add_country(COUNTRIES, "Cameroun", "Afrique", "Français, Anglais", "25000000", "Franc CFA", "6", "Vert, Rouge, Jaune");
    add_country(COUNTRIES, "Canada", "Amerique", "Anglais, Français", "38000000", "Dollar canadien", "1", "Rouge, Blanc");
    add_country(COUNTRIES, "Cap-Vert", "Afrique", "Portugais", "555000", "Escudo cap-verdien", "0", "Bleu, Blanc, Rouge, Jaune");
    add_country(COUNTRIES, "Republique_centrafricaine", "Afrique", "Sango, Français", "4700000", "Franc CFA", "6", "Bleu, Blanc, Rouge, Vert, Jaune");
    add_country(COUNTRIES, "Tchad", "Afrique", "Français, Arabe", "16000000", "Franc CFA", "6", "Bleu, Jaune, Rouge");
    add_country(COUNTRIES, "Chili", "Amerique", "Espagnol", "19000000", "Peso chilien", "3", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Chine", "Asie", "Mandarin", "1398000000", "Yuan", "14", "Rouge, Jaune");
    add_country(COUNTRIES, "Colombie", "Amerique", "Espagnol", "50000000", "Peso colombien", "5", "Jaune, Bleu, Rouge");
    add_country(COUNTRIES, "Comores", "Afrique", "Comorien, Arabe, Français", "869000", "Franc comorien", "0", "Vert, Jaune, Blanc, Rouge, Bleu");
    add_country(COUNTRIES, "Republique_du_Congo", "Afrique", "Français", "5200000", "Franc CFA", "5", "Vert, Jaune, Rouge");
    add_country(COUNTRIES, "Republique_democratique_du_Congo", "Afrique", "Français", "89000000", "Franc congolais", "9", "Bleu, Rouge, Jaune");
    add_country(COUNTRIES, "Costa_Rica", "Amerique", "Espagnol", "5000000", "Colón costaricain", "2", "Bleu, Blanc, Rouge");
    add_country(COUNTRIES, "Croatie", "Europe", "Croate", "4000000", "Kuna", "5", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Cuba", "Amerique", "Espagnol", "11000000", "Peso cubain", "0", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Chypre", "Europe", "Grec, Turc", "1200000", "Euro", "1", "Blanc, Orange, Vert");
    add_country(COUNTRIES, "Republique Tcheque", "Europe", "Tcheque", "10700000", "Couronne tcheque", "4", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Danemark", "Europe", "Danois", "5800000", "Couronne danoise", "1", "Rouge, Blanc");
    add_country(COUNTRIES, "Djibouti", "Afrique", "Français, Arabe", "1000000", "Franc djiboutien", "3", "Vert, Blanc, Bleu, Rouge");
    add_country(COUNTRIES, "Dominique", "Amerique", "Anglais", "72,000", "Dollar des Caraibes orientales", "0", "Vert, Jaune, Rouge, Noir");
    add_country(COUNTRIES, "Republique dominicaine", "Amerique", "Espagnol", "10800000", "Peso dominicain", "1", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Equateur", "Amerique", "Espagnol", "17000000", "Dollar americain", "2", "Jaune, Bleu, Rouge");
    add_country(COUNTRIES, "Egypte", "Afrique", "Arabe", "100000000", "Livre egyptienne", "4", "Rouge, Blanc, Noir");
    add_country(COUNTRIES, "El_Salvador", "Amerique", "Espagnol", "6500000", "Dollar americain", "2", "Bleu, Blanc");
    add_country(COUNTRIES, "Guinee_equatoriale", "Afrique", "Espagnol, Français, Portugais", "1400000", "Franc CFA", "3", "Vert, Blanc, Rouge, Bleu");
    add_country(COUNTRIES, "Erythree", "Afrique", "Tigrigna, Arabe, Anglais", "3500000", "Nakfa", "3", "Vert, Bleu, Rouge");
    add_country(COUNTRIES, "Estonie", "Europe", "Estonien", "1300000", "Euro", "2", "Bleu, Noir, Blanc");
    add_country(COUNTRIES, "Eswatini", "Afrique", "Swati, Anglais", "1100000", "Lilangeni", "2", "Bleu, Jaune, Rouge, Blanc");
    add_country(COUNTRIES, "ethiopie", "Afrique", "Amharique", "112000000", "Birr", "6", "Vert, Jaune, Rouge");
    add_country(COUNTRIES, "Fidji", "Oceanie", "Anglais, Fidjien, Hindoustani", "896000", "Dollar fidjien", "0", "Bleu, Blanc, Rouge");
    add_country(COUNTRIES, "Finlande", "Europe", "Finnois, Suedois", "5500000", "Euro", "3", "Bleu, Blanc");
    add_country(COUNTRIES, "France", "Europe", "Français", "67000000", "Euro", "8", "Bleu, Blanc, Rouge");
    add_country(COUNTRIES, "Gabon", "Afrique", "Français", "2100000", "Franc CFA", "3", "Vert, Jaune, Bleu");
    add_country(COUNTRIES, "Gambie", "Afrique", "Anglais", "2400000", "Dalasi", "2", "Rouge, Bleu, Vert, Blanc");
    add_country(COUNTRIES, "Georgie", "Asie", "Georgien", "3700000", "Lari", "4", "Rouge, Blanc");
    add_country(COUNTRIES, "Allemagne", "Europe", "Allemand", "83000000", "Euro", "9", "Noir, Rouge, Jaune");
    add_country(COUNTRIES, "Ghana", "Afrique", "Anglais", "31000000", "Cedi", "3", "Rouge, Jaune, Vert, Noir");
    add_country(COUNTRIES, "Grece", "Europe", "Grec", "10400000", "Euro", "4", "Bleu, Blanc");
    add_country(COUNTRIES, "Grenade", "Amerique", "Anglais", "113000", "Dollar des Caraibes orientales", "0", "Rouge, Jaune, Vert");
    add_country(COUNTRIES, "Guatemala", "Amerique", "Espagnol", "17000000", "Quetzal", "4", "Bleu, Blanc");
    add_country(COUNTRIES, "Guinee", "Afrique", "Français", "13000000", "Franc guineen", "6", "Rouge, Jaune, Vert");
    add_country(COUNTRIES, "Guinee-Bissau", "Afrique", "Portugais", "2000000", "Franc CFA", "5", "Rouge, Jaune, Vert");
    add_country(COUNTRIES, "Guyana", "Amerique", "Anglais", "786000", "Dollar guyanien", "2", "Vert, Jaune, Rouge, Noir, Blanc");
    add_country(COUNTRIES, "Haiti", "Amerique", "Creole haitien, Français", "11000000", "Gourde", "1", "Bleu, Rouge");
    add_country(COUNTRIES, "Honduras", "Amerique", "Espagnol", "9500000", "Lempira", "3", "Bleu, Blanc");
    add_country(COUNTRIES, "Hongrie", "Europe", "Hongrois", "9600000", "Forint", "7", "Rouge, Blanc, Vert");
    add_country(COUNTRIES, "Islande", "Europe", "Islandais", "364000", "Couronne islandaise", "0", "Bleu, Blanc, Rouge");
    add_country(COUNTRIES, "Inde", "Asie", "Hindi, Anglais", "1366000000", "Roupie", "6", "Orange, Blanc, Vert");
    add_country(COUNTRIES, "Indonesie", "Asie", "Indonesien", "270000000", "Roupie indonesienne", "3", "Rouge, Blanc");
    add_country(COUNTRIES, "Iran", "Asie", "Persan", "83000000", "Rial iranien", "7", "Vert, Blanc, Rouge");
    add_country(COUNTRIES, "Irak", "Asie", "Arabe, Kurde", "40000000", "Dinar irakien", "6", "Rouge, Blanc, Noir, Vert");
    add_country(COUNTRIES, "Irlande", "Europe", "Irlandais, Anglais", "4900000", "Euro", "1", "Vert, Blanc, Orange");
    add_country(COUNTRIES, "Israël", "Asie", "Hebreu, Arabe", "9000000", "Shekel", "5", "Bleu, Blanc");
    add_country(COUNTRIES, "Italie", "Europe", "Italien", "60000000", "Euro", "6", "Vert, Blanc, Rouge");
    add_country(COUNTRIES, "Jamaique", "Amerique", "Anglais", "2900000", "Dollar jamaicain", "0", "Noir, Vert, Jaune");
    add_country(COUNTRIES, "Japon", "Asie", "Japonais", "126000000", "Yen", "0", "Rouge, Blanc");
    add_country(COUNTRIES, "Jordanie", "Asie", "Arabe", "10000000", "Dinar jordanien", "5", "Rouge, Blanc, Noir, Vert");
    add_country(COUNTRIES, "Kazakhstan", "Asie", "Kazakh, Russe", "18700000", "Tenge", "5", "Bleu, Jaune");
    add_country(COUNTRIES, "Kenya", "Afrique", "Swahili, Anglais", "53000000", "Shilling kenyan", "5", "Noir, Rouge, Vert");
    add_country(COUNTRIES, "Kiribati", "Oceanie", "Anglais, Gilbertin", "119000", "Dollar australien", "0", "Bleu, Rouge, Blanc, Jaune");
    add_country(COUNTRIES, "Coree_du_Nord", "Asie", "Coreen", "25000000", "Won nord-coreen", "3", "Rouge, Bleu, Blanc");
    add_country(COUNTRIES, "Coree_du_Sud", "Asie", "Coreen", "51000000", "Won sud-coreen", "1", "Blanc, Rouge, Bleu, Noir");
    add_country(COUNTRIES, "Koweit", "Asie", "Arabe", "4200000", "Dinar koweitien", "2", "Vert, Blanc, Rouge, Noir");
    add_country(COUNTRIES, "Kirghizistan", "Asie", "Kirghize, Russe", "6500000", "Som", "4", "Rouge, Jaune");
    add_country(COUNTRIES, "Laos", "Asie", "Lao", "7300000", "Kip", "5", "Rouge, Bleu, Blanc");
    add_country(COUNTRIES, "Lettonie", "Europe", "Letton", "1900000", "Euro", "4", "Rouge, Blanc");
    add_country(COUNTRIES, "Liban", "Asie", "Arabe", "6800000", "Livre libanaise", "2", "Rouge, Blanc, Vert");
    add_country(COUNTRIES, "Lesotho", "Afrique", "Anglais, Sesotho", "2100000", "Loti", "2", "Bleu, Blanc, Vert");
    add_country(COUNTRIES, "Liberia", "Afrique", "Anglais", "5000000", "Dollar liberien", "3", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Libye", "Afrique", "Arabe", "6800000", "Dinar libyen", "6", "Rouge, Noir, Vert");
    add_country(COUNTRIES, "Liechtenstein", "Europe", "Allemand", "38000", "Franc suisse", "2", "Bleu, Rouge");
    add_country(COUNTRIES, "Lituanie", "Europe", "Lituanien", "2800000", "Euro", "4", "Jaune, Vert, Rouge");
    add_country(COUNTRIES, "Luxembourg", "Europe", "Luxembourgeois, Français, Allemand", "634000", "Euro", "3", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Madagascar", "Afrique", "Malagasy, Français", "27000000", "Ariary", "4", "Rouge, Vert, Blanc");
    add_country(COUNTRIES, "Malawi", "Afrique", "Anglais, Chichewa", "19000000", "Kwacha", "3", "Noir, Rouge, Vert");
    add_country(COUNTRIES, "Malaisie", "Asie", "Malais", "32000000", "Ringgit", "3", "Jaune, Bleu, Rouge, Blanc");
    add_country(COUNTRIES, "Maldives", "Asie", "Dhivehi", "540000", "Rufiyaa", "0", "Rouge, Vert, Blanc");
    add_country(COUNTRIES, "Mali", "Afrique", "Français", "19000000", "Franc CFA", "7", "Vert, Jaune, Rouge");
    add_country(COUNTRIES, "Malte", "Europe", "Maltais, Anglais", "514000", "Euro", "0", "Rouge, Blanc");
    add_country(COUNTRIES, "Iles_Marshall", "Oceanie", "Anglais, Marshallais", "59,000", "Dollar americain", "0", "Bleu, Orange, Blanc");
    add_country(COUNTRIES, "Mauritanie", "Afrique", "Arabe", "4500000", "Ouguiya", "3", "Vert, Jaune");
    add_country(COUNTRIES, "Maurice", "Afrique", "Anglais", "1300000", "Roupie mauricienne", "0", "Rouge, Bleu, Jaune, Vert");
    add_country(COUNTRIES, "Mexique", "Amerique", "Espagnol", "128000000", "Peso mexicain", "3", "Vert, Blanc, Rouge");
    add_country(COUNTRIES, "Micronesie", "Oceanie", "Anglais", "115000", "Dollar americain", "0", "Bleu, Blanc");
    add_country(COUNTRIES, "Moldavie", "Europe", "Roumain", "2600000", "Leu", "2", "Bleu, Jaune, Rouge");
    add_country(COUNTRIES, "Monaco", "Europe", "Français", "39000", "Euro", "0", "Rouge, Blanc");
    add_country(COUNTRIES, "Mongolie", "Asie", "Mongol", "3200000", "Tugrik", "2", "Rouge, Bleu");
    add_country(COUNTRIES, "Montenegro", "Europe", "Montenegrin", "622000", "Euro", "5", "Rouge, Jaune");
    add_country(COUNTRIES, "Maroc", "Afrique", "Arabe", "36000000", "Dirham", "3", "Rouge, Vert");
    add_country(COUNTRIES, "Mozambique", "Afrique", "Portugais", "31000000", "Metical", "6", "Vert, Noir, Jaune, Blanc, Rouge");
    add_country(COUNTRIES, "Myanmar", "Asie", "Birman", "54000000", "Kyat", "5", "Jaune, Vert, Rouge");
    add_country(COUNTRIES, "Namibie", "Afrique", "Anglais", "2500000", "Dollar namibien", "2", "Bleu, Rouge, Vert, Blanc, Jaune");
    add_country(COUNTRIES, "Nauru", "Oceanie", "Nauruan, Anglais", "10000", "Dollar australien", "0", "Bleu, Jaune");
    add_country(COUNTRIES, "Nepal", "Asie", "Nepalais", "29000000", "Roupie nepalaise", "2", "Rouge, Bleu");
    add_country(COUNTRIES, "Pays-Bas", "Europe", "Neerlandais", "17000000", "Euro", "2", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Nouvelle-Zelande", "Oceanie", "Anglais, Maori", "5000000", "Dollar neo-zelandais", "0", "Bleu, Rouge, Blanc");
    add_country(COUNTRIES, "Nicaragua", "Amerique", "Espagnol", "6500000", "Córdoba", "2", "Bleu, Blanc");
    add_country(COUNTRIES, "Niger", "Afrique", "Français", "24000000", "Franc CFA", "7", "Orange, Blanc, Vert");
    add_country(COUNTRIES, "Nigeria", "Afrique", "Anglais", "206000000", "Naira", "4", "Vert, Blanc");
    add_country(COUNTRIES, "Norvege", "Europe", "Norvegien", "5400000", "Couronne norvegienne", "1", "Rouge, Bleu, Blanc");
    add_country(COUNTRIES, "Oman", "Asie", "Arabe", "5000000", "Rial omanais", "3", "Rouge, Blanc, Vert");
    add_country(COUNTRIES, "Pakistan", "Asie", "Ourdou, Anglais", "220000000", "Roupie pakistanaise", "4", "Vert, Blanc");
    add_country(COUNTRIES, "Palaos", "Oceanie", "Anglais, Paluan", "18000", "Dollar americain", "0", "Bleu, Jaune");
    add_country(COUNTRIES, "Palestine", "Asie", "Arabe", "5000000", "Shekel israelien, Dinar jordanien", "4", "Noir, Blanc, Vert, Rouge");
    add_country(COUNTRIES, "Panama", "Amerique", "Espagnol", "4300000", "Balboa", "2", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Papouasie-Nouvelle-Guinee", "Oceanie", "Anglais, Tok Pisin, Hiri Motu", "9000000", "Kina", "1", "Noir, Rouge, Jaune");
    add_country(COUNTRIES, "Paraguay", "Amerique", "Espagnol, Guarani", "7000000", "Guarani", "3", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Perou", "Amerique", "Espagnol, Quechua, Aymara", "33000000", "Sol", "5", "Rouge, Blanc");
    add_country(COUNTRIES, "Philippines", "Asie", "Filipino, Anglais", "109000000", "Peso philippin", "3", "Rouge, Blanc, Bleu, Jaune");
    add_country(COUNTRIES, "Pologne", "Europe", "Polonais", "38000000", "Zloty", "7", "Blanc, Rouge");
    add_country(COUNTRIES, "Portugal", "Europe", "Portugais", "10000000", "Euro", "1", "Vert, Rouge");
    add_country(COUNTRIES, "Qatar", "Asie", "Arabe", "2800000", "Rial qatari", "1", "Marron, Blanc");
    add_country(COUNTRIES, "Roumanie", "Europe", "Roumain", "19000000", "Leu", "5", "Bleu, Jaune, Rouge");
    add_country(COUNTRIES, "Russie", "Europe, Asie", "Russe", "144000000", "Rouble", "16", "Blanc, Bleu, Rouge");
    add_country(COUNTRIES, "Rwanda", "Afrique", "Kinyarwanda, Français, Anglais", "12000000", "Franc rwandais", "4", "Bleu, Jaune, Vert");
    add_country(COUNTRIES, "Saint-Christophe-et-Nieves", "Amerique", "Anglais", "53000", "Dollar des Caraibes orientales", "0", "Vert, Jaune, Rouge, Noir");
    add_country(COUNTRIES, "Sainte-Lucie", "Amerique", "Anglais", "183000", "Dollar des Caraibes orientales", "0", "Bleu, Jaune, Noir, Blanc");
    add_country(COUNTRIES, "Saint-Vincent-et-les-Grenadines", "Amerique", "Anglais", "110000", "Dollar des Caraibes orientales", "0", "Bleu, Jaune, Vert");
    add_country(COUNTRIES, "Samoa", "Oceanie", "Samoan, Anglais", "198000", "Tala", "0", "Rouge, Bleu, Blanc");
    add_country(COUNTRIES, "Saint-Marin", "Europe", "Italien", "34000", "Euro", "2", "Bleu, Blanc");
    add_country(COUNTRIES, "Sao_Tome-et-Principe", "Afrique", "Portugais", "219000", "Dobra", "0", "Vert, Jaune, Rouge");
    add_country(COUNTRIES, "Arabie_Saoudite", "Asie", "Arabe", "34000000", "Riyal saoudien", "8", "Vert, Blanc");
    add_country(COUNTRIES, "Senegal", "Afrique", "Français", "16000000", "Franc CFA", "5", "Vert, Jaune, Rouge");
    add_country(COUNTRIES, "Serbie", "Europe", "Serbe", "7000000", "Dinar serbe", "8", "Rouge, Bleu, Blanc");
    add_country(COUNTRIES, "Seychelles", "Afrique", "Creole seychellois, Anglais, Français", "98000", "Roupie seychelloise", "0", "Rouge, Blanc, Bleu, Jaune, Vert");
    add_country(COUNTRIES, "Sierra_Leone", "Afrique", "Anglais", "8000000", "Leone", "6", "Vert, Blanc, Bleu");
    add_country(COUNTRIES, "Singapour", "Asie", "Anglais, Malais, Mandarin, Tamoul", "5700000", "Dollar de Singapour", "0", "Rouge, Blanc");
    add_country(COUNTRIES, "Slovaquie", "Europe", "Slovaque", "5400000", "Euro", "5", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Slovenie", "Europe", "Slovene", "2100000", "Euro", "4", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Iles_Salomon", "Oceanie", "Anglais", "686000", "Dollar des Iles Salomon", "0", "Bleu, Jaune, Vert");
    add_country(COUNTRIES, "Somalie", "Afrique", "Somali", "15400000", "Shilling somalien", "6", "Bleu, Blanc");
    add_country(COUNTRIES, "Afrique_du_Sud", "Afrique", "Anglais, Afrikaans, Zoulou, Xhosa", "58000000", "Rand", "6", "Vert, Jaune, Rouge, Bleu, Noir, Blanc");
    add_country(COUNTRIES, "Soudan_du_Sud", "Afrique", "Anglais", "11000000", "Livre sud-soudanaise", "6", "Noir, Rouge, Vert, Bleu, Blanc, Jaune");
    add_country(COUNTRIES, "Espagne", "Europe", "Espagnol", "47000000", "Euro", "5", "Rouge, Jaune");
    add_country(COUNTRIES, "Sri_Lanka", "Asie", "Cinghalais, Tamoul", "21000000", "Roupie sri-lankaise", "0", "Rouge, Jaune, Vert, Orange");
    add_country(COUNTRIES, "Soudan", "Afrique", "Arabe", "43000000", "Livre soudanaise", "7", "Rouge, Blanc, Noir, Vert");
    add_country(COUNTRIES, "Suriname", "Amerique", "Neerlandais", "586,000", "Dollar surinamais", "3", "Vert, Blanc, Rouge, Jaune");
    add_country(COUNTRIES, "Suede", "Europe", "Suedois", "10000000", "Couronne suedoise", "2", "Bleu, Jaune");
    add_country(COUNTRIES, "Suisse", "Europe", "Allemand, Français, Italien, Romanche", "8500000", "Franc suisse", "5", "Rouge, Blanc");
    add_country(COUNTRIES, "Syrie", "Asie", "Arabe", "17500000", "Livre syrienne", "5", "Rouge, Blanc, Noir, Vert");
    add_country(COUNTRIES, "Tadjikistan", "Asie", "Tadjik", "9500000", "Somoni", "4", "Rouge, Blanc, Vert");
    add_country(COUNTRIES, "Tanzanie", "Afrique", "Swahili, Anglais", "58000000", "Shilling tanzanien", "8", "Vert, Jaune, Noir, Bleu");
    add_country(COUNTRIES, "Thailande", "Asie", "Thai", "69000000", "Baht", "4", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Timor oriental", "Asie", "Tetum, Portugais", "1300000", "Dollar americain", "3", "Rouge, Jaune, Noir, Blanc");
    add_country(COUNTRIES, "Togo", "Afrique", "Français", "8000000", "Franc CFA", "3", "Vert, Jaune, Rouge, Blanc");
    add_country(COUNTRIES, "Tonga", "Oceanie", "Tongien, Anglais", "105000", "Pa'anga", "0", "Rouge, Blanc");
    add_country(COUNTRIES, "Trinite-et-Tobago", "Amerique", "Anglais", "1400000", "Dollar trinidadien", "0", "Rouge, Blanc, Noir");
    add_country(COUNTRIES, "Tunisie", "Afrique", "Arabe", "12000000", "Dinar tunisien", "2", "Rouge, Blanc");
    add_country(COUNTRIES, "Turquie", "Europe/Asie", "Turc", "84000000", "Livre turque", "8", "Rouge, Blanc");
    add_country(COUNTRIES, "Turkmenistan", "Asie", "Turkmene", "6000000", "Manat", "4", "Vert, Blanc, Rouge");
    add_country(COUNTRIES, "Tuvalu", "Oceanie", "Tuvaluan, Anglais", "11000", "Dollar australien", "0", "Bleu, Jaune");
    add_country(COUNTRIES, "Ouganda", "Afrique", "Anglais, Swahili", "42000000", "Shilling ougandais", "5", "Noir, Jaune, Rouge");
    add_country(COUNTRIES, "Ukraine", "Europe", "Ukrainien", "41000000", "Hryvnia", "7", "Bleu, Jaune");
    add_country(COUNTRIES, "Emirats_arabes_unis", "Asie", "Arabe", "9800000", "Dirham des emirats arabes unis", "5", "Rouge, Vert, Blanc, Noir");
    add_country(COUNTRIES, "Royaume-Uni", "Europe", "Anglais", "66000000", "Livre sterling", "1", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Etats-Unis", "Amerique", "Anglais", "331000000", "Dollar americain", "2", "Rouge, Blanc, Bleu");
    add_country(COUNTRIES, "Uruguay", "Amerique", "Espagnol", "3500000", "Peso uruguayen", "2", "Bleu, Blanc");
    add_country(COUNTRIES, "Ouzbekistan", "Asie", "Ouzbek", "33000000", "Som", "5", "Bleu, Blanc, Vert");
    add_country(COUNTRIES, "Vanuatu", "Oceanie", "Bichelamar, Anglais, Français", "307000", "Vatu", "0", "Vert, Rouge, Noir, Jaune");
    add_country(COUNTRIES, "Vatican", "Europe", "Italien, Latin", "800", "Euro", "0", "Jaune, Blanc");
    add_country(COUNTRIES, "Venezuela", "Amerique", "Espagnol", "28000000", "Bolivar", "3", "Jaune, Bleu, Rouge");
    add_country(COUNTRIES, "Vietnam", "Asie", "Vietnamien", "96000000", "Dong", "3", "Rouge, Jaune");
    add_country(COUNTRIES, "Yemen", "Asie", "Arabe", "30000000", "Rial yemenite", "2", "Rouge, Blanc, Noir");
    add_country(COUNTRIES, "Zambie", "Afrique", "Anglais", "18000000", "Kwacha zambien", "8", "Vert, Rouge, Noir, Orange");
    add_country(COUNTRIES, "Zimbabwe", "Afrique", "Anglais, Shona, Ndebele", "15000000", "Dollar zimbabween", "4", "Vert, Jaune, Rouge, Noir");
}